In [27]:
import numpy as np

<img src="AIAYN_Draft_230426_85.png" alt="Eq (1) of Attention is All You Need" />

In [24]:
# set query, q, to "attitude"
q = "attitude"
q

'attitude'

<img src="AIAYN_Draft_230426_86.png" alt="A simple python dict" />

In [28]:
# Make dict with keys and values
KVdict = {
    "cat" : "jinx",
    "medicine" : "meh",
    "taste" : "bitter",
    "attitude" : "yes",
    "disposition" : "fickle"}
KVdict

{'cat': 'jinx',
 'medicine': 'meh',
 'taste': 'bitter',
 'attitude': 'yes',
 'disposition': 'fickle'}

In [29]:
# Standard Python dict q, K, V result
KVdict[q]

'yes'

<img src="AIAYN_Draft_230426_87.png" alt="1-hot vector mappings of keys and queries" />

In [26]:
# Make dict of mappings of keys to 1-hot vectors (tuples)
Vec1hmap = {
    "cat" : (1,0,0,0,0,0,0,0,0,0),
    "medicine" : (0,1,0,0,0,0,0,0,0,0),
    "taste" : (0,0,1,0,0,0,0,0,0,0),
    "attitude" : (0,0,0,1,0,0,0,0,0,0),
    "disposition" : (0,0,0,0,1,0,0,0,0,0),
    "jinx" : (0,0,0,0,0,1,0,0,0,0),
    "meh" : (0,0,0,0,0,0,1,0,0,0),
    "bitter" : (0,0,0,0,0,0,0,1,0,0),
    "yes" : (0,0,0,0,0,0,0,0,1,0),
    "fickle" : (0,0,0,0,0,0,0,0,0,1)}
Vec1hmap

{'cat': (1, 0, 0, 0, 0, 0, 0, 0, 0, 0),
 'medicine': (0, 1, 0, 0, 0, 0, 0, 0, 0, 0),
 'taste': (0, 0, 1, 0, 0, 0, 0, 0, 0, 0),
 'attitude': (0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
 'disposition': (0, 0, 0, 0, 1, 0, 0, 0, 0, 0),
 'jinx': (0, 0, 0, 0, 0, 1, 0, 0, 0, 0),
 'meh': (0, 0, 0, 0, 0, 0, 1, 0, 0, 0),
 'bitter': (0, 0, 0, 0, 0, 0, 0, 1, 0, 0),
 'yes': (0, 0, 0, 0, 0, 0, 0, 0, 1, 0),
 'fickle': (0, 0, 0, 0, 0, 0, 0, 0, 0, 1)}

In [32]:
K1map = {"cat"         : Vec1hmap["cat"],
         "medicine"    : Vec1hmap["medicine"],
         "taste"       : Vec1hmap["taste"],
         "attitude"    : Vec1hmap["attitude"],
         "disposition" : Vec1hmap["disposition"],
        }
K1map

{'cat': (1, 0, 0, 0, 0, 0, 0, 0, 0, 0),
 'medicine': (0, 1, 0, 0, 0, 0, 0, 0, 0, 0),
 'taste': (0, 0, 1, 0, 0, 0, 0, 0, 0, 0),
 'attitude': (0, 0, 0, 1, 0, 0, 0, 0, 0, 0),
 'disposition': (0, 0, 0, 0, 1, 0, 0, 0, 0, 0)}

In [34]:
V1map = {Vec1hmap["jinx"]  : "jinx",
         Vec1hmap["meh"]   : "meh",
         Vec1hmap["bitter"]: "bitter",
         Vec1hmap["yes"]   : "yes",
         Vec1hmap["fickle"]: "fickle",
        }
V1map

{(0, 0, 0, 0, 0, 1, 0, 0, 0, 0): 'jinx',
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 0): 'meh',
 (0, 0, 0, 0, 0, 0, 0, 1, 0, 0): 'bitter',
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 0): 'yes',
 (0, 0, 0, 0, 0, 0, 0, 0, 0, 1): 'fickle'}

In [5]:
# Make dict of vector (immutable tuple for hashing) mappings of 
# 1-hots to tokens
Vec2token = {
    (1,0,0,0,0,0,0,0,0,0) : "cat",
    (0,1,0,0,0,0,0,0,0,0) : "medicine",
    (0,0,1,0,0,0,0,0,0,0) : "taste",
    (0,0,0,1,0,0,0,0,0,0) : "attitude",
    (0,0,0,0,1,0,0,0,0,0) : "disposition",
    (0,0,0,0,0,1,0,0,0,0) : "jinx",
    (0,0,0,0,0,0,1,0,0,0) : "meh",
    (0,0,0,0,0,0,0,1,0,0) : "bitter",
    (0,0,0,0,0,0,0,0,1,0) : "yes",
    (0,0,0,0,0,0,0,0,0,1) : "fickle"}
Vec2token

{(1, 0, 0, 0, 0, 0, 0, 0, 0, 0): 'cat',
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0): 'medicine',
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0): 'taste',
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0): 'attitude',
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0): 'disposition',
 (0, 0, 0, 0, 0, 1, 0, 0, 0, 0): 'jinx',
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 0): 'meh',
 (0, 0, 0, 0, 0, 0, 0, 1, 0, 0): 'bitter',
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 0): 'yes',
 (0, 0, 0, 0, 0, 0, 0, 0, 0, 1): 'fickle'}

<img src="AIAYN_Draft_230426_88.png" alt="1-hot vector mappings of keys and queries" />

In [6]:
# Get 1-hot query mapping from query, q; q1h is a 1-hot vector (tuple)
q1h = Vec1hmap[q]
q1h

(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)

In [36]:
# Make dict with 1-hot vector mapped versions of keys
K1Vdict = {
    K1map["cat"] : "jinx",
    K1map["medicine"] : "meh",
    K1map["taste"] : "bitter",
    K1map["attitude"] : "yes",
    K1map["disposition"] : "fickle"}
K1Vdict

{(1, 0, 0, 0, 0, 0, 0, 0, 0, 0): 'jinx',
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0): 'meh',
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0): 'bitter',
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0): 'yes',
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0): 'fickle'}

In [37]:
# Standard Python dict q, K, V result where q1h and K1h are 1-hot 
# mappings of q and K 
K1Vdict[q1h]

'yes'

<img src="AIAYN_Draft_230426_89.png" alt="Finding the value where the dot product between query and key is maximal" />

In [38]:
# Find key where dot product of q1h and K1h is maximal and return the
# value at that key
K1h = list(K1Vdict.keys())
# Given K1Vdict 1-hot representations of keys, select v1h with max dot
# product of q1h with K1h
K1Vdict[K1h[np.argmax(np.dot(q1h, np.array(K1h).transpose()))]]

'yes'

<img src="AIAYN_Draft_230426_90.png" alt="Mapping both keys and values to 1-hots" />

In [39]:
# Make dict with 1-hot vector mapped versions of keys and values
K1V1dict = {
    K1map["cat"] : Vec1hmap["jinx"],
    K1map["medicine"] : Vec1hmap["meh"],
    K1map["taste"] : Vec1hmap["bitter"],
    K1map["attitude"] : Vec1hmap["yes"],
    K1map["disposition"] : Vec1hmap["fickle"]}
K1V1dict

{(1, 0, 0, 0, 0, 0, 0, 0, 0, 0): (0, 0, 0, 0, 0, 1, 0, 0, 0, 0),
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0): (0, 0, 0, 0, 0, 0, 1, 0, 0, 0),
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0): (0, 0, 0, 0, 0, 0, 0, 1, 0, 0),
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0): (0, 0, 0, 0, 0, 0, 0, 0, 1, 0),
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0): (0, 0, 0, 0, 0, 0, 0, 0, 0, 1)}

<img src="AIAYN_Draft_230426_91.png" alt="Weighted dot products of query vector with values vectors" />

In [43]:
# Extract matrix, K (1-hots)
K = np.array(list(K1V1dict.keys()))
K

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [44]:
# Extract matrix, V (1-hots)
V = np.array(list(K1V1dict.values()))
V

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [45]:
# Given K1V1dict 1-hot representations of keys and values, weight 
# V by dot product of q1h with K; map 1-hot value back to 
# token value via Vec2token lookup
Vec2token[tuple(np.matmul(np.dot(q1h, K.transpose()),V))]

'yes'

<img src="AIAYN_Draft_230426_92.png" alt="Scaled weighted dot products of query vector with and values matrix" />

In [48]:
# Normalizer, d_k, for no softmax and orthonormal vectors
d_k = 1.0
d_k

1.0

In [49]:
# Given K1V1dict 1-hot representations of keys and values, 
# compute 1-hot encoding of value from AIAYN matrix version 
# of self-attention via matrix multiply; map 1-hot value back
# to token value via Vec2token
Vec2token[tuple(np.matmul(np.matmul(q1h, K.transpose())/np.sqrt(d_k),V))]

'yes'

<img src="AIAYN_Draft_230426_93.png" alt="Scaled dot attention with query, keys and values matrices -- full equivalence to AIAYN" />

In [50]:
print("Reminder: equivalent python dict:")
print("KVdict = ")
print(KVdict)

all_queries = list(KVdict.keys())
print()
print("all queries : " + str(all_queries))
Q = np.array([Vec1hmap[k] for k in list(KVdict.keys())])
print()
print("Q = ")
print(Q)

# Given K1V1dict 1-hot representations of keys and values, 
# compute 1-hot encoding of value from AIAYN matrix version 
# of self-attention via matrix multiply; map 1-hot value back
# to token value via Vec2token
Att = np.matmul(np.matmul(Q, K.transpose())/np.sqrt(d_k),V)
Att

print()
print("Attention(Q,K,V) = ")
print(Att)

print()
[Vec2token[k] for k in list(map(tuple, Att))]

Reminder: equivalent python dict:
KVdict = 
{'cat': 'jinx', 'medicine': 'meh', 'taste': 'bitter', 'attitude': 'yes', 'disposition': 'fickle'}

all queries : ['cat', 'medicine', 'taste', 'attitude', 'disposition']

Q = 
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]

Attention(Q,K,V) = 
[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0]]



['jinx', 'meh', 'bitter', 'yes', 'fickle']

<img src="AIAYN_Draft_230426_94.png" alt="Full equivalence to AIAYN example Q.E.D." />